### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by flatsiedatsie** [vikas-kukreti/js-playground#1]
Thank you for this wonderful little project.

I noticed an error when using it:

```
in.js:84 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at executeCode (main.js:84:50)
    at HTMLDocument.<anonymous> (main.js:28:5)
e
```

Which is this code:

```
      if(e.lineNumber == undefined)
            e.lineNumber = e.stack.split('>:')[1].split(':')[0];
        codeOutput.innerHTML += '<h4 style="color: #ff5555">Problem at line number: <span style="color: #f0f0f0">' + e.lineNumber + '</span></h4>';
  
```

I've made some minor modifications (backup of the current text & run the code after eack keystroke), but since they are not modification of the code itself they shouldn't be the cause?

Another question: under what license is this code available?

**Comment by vikas-kukreti** [comment]
Which OS and Browser you are using ?

**Comment by flatsiedatsie** [comment]
MacOS and Brave. But I've since fixed the issue.

I've made some cool modifications (upgraded to CodeMirror6, and moved from eval to a webworker), but I will only release the project to the public if you allow that. Could you state the license under which the original code is available, if any?
